config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :books, only: [:show, :index, :new, :create, :edit, :update]
  root 'welcome#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
   
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/books.rb
class Books < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :author, presence: true, length: { minimum: 6, maximum: 100 }
    validates :book_count, presence: true, length: { minimum: 1, maximum: 2}
end

app/models/library.rb
class Library < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # before_save :copy_data
  # after_save :copy_data


  def set_default_role
    self.role ||= :user
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, address_attributes: [:country, :state, :city, :area, :postal_code]])
    end
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Books.all
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Books.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Books was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Books was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_index_url, notice: "Books was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Books.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :book_count, :author)
    end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]

  # GET /libraries or /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to library_url(@library), notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to library_url(@library), notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.require(:library).permit(:role, :book_count, :mname, :titile, :issued_at)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    def create
  
      if sign_up_params[:role]=='user'
        @stud = Student.find_by_email(sign_up_params[:email])
        if @stud.nil?
          @stud = Student.new(email: sign_up_params[:email], name: params[:user][:student][:name],
                              password: sign_up_params[:password], education: params[:user][:student][:education],
                              university: params[:user][:student][:university], max_books:2, fines: 0)
          if @stud.save
            if(@stud[:education]=="Masters")
              @stud.update({max_books:4})
            elsif (@stud[:education]=="PhD")
              @stud.update({max_books:6})
            else
              @stud.update({max_books:2})
            end
          end
          super and return
          # redirect_to :student and return
        else
          # @stud.update(student_signup_params)
          # format.html { redirect_to students_path, notice: 'Student was successfully created.' }
          # format.json { render :show, status: :created, location: @student }
        end
      elsif sign_up_params[:role]=='librarian'
        @lib = Librarian.find_by_email(sign_up_params[:email])
        if(@lib.nil?)
          @lib = Librarian.new(email: sign_up_params[:email], name: params[:user][:librarian][:name],
                               password: sign_up_params[:password], libraries_id: params[:user][:librarian][:libraries_id],
                               approved: false)
          @lib.save
          redirect_to new_user_session_path, :flash=>{:alert => 'Request has been sent. Pending admin approval.'}
          # format.json { render :show, status: :accepted, location: home_index_path}
        else
          # @lib.update(librarian_signup_parmas)
          # format.html { redirect_to librarians_path, notice: 'Student was successfully created.' }
          # format.json { render :show, status: :created, location: @librarian }
        end
      else
        redirect_to new_user_session_path, :flash =>{:alert =>'Redirected to user homepage.'}
      end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_books.html.erb
<div id="<%= dom_id books %>">
  <p>
    <strong>Title:</strong>
    <%= books.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= books.description %>
  </p>

  <p>
    <strong>Book count:</strong>
    <%= books.book_count %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= books.author %>
  </p>

</div>

app/views/books/edit.html.erb
<h1>Edit books</h1>

<% if @book.errors.any? %>
  <h2>The following errors prevented the book from being saved</h2>
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @book, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :author %><br/>
    <%= f.text_area :author %>
  </p>

  <p>
    <%= f.label :book_count %><br/>
    <%= f.number_field :book_count %>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/books/index.html.erb
<h1>Books listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Book_count</th>

    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= book.book_count %></td>

    
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>Create a new Book</h1>

<% if @book.errors.any? %>
  <h2>The following errors prevented the book from being saved</h2>
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with scope: :book, url: books_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :author %><br/>
    <%= f.text_area :author %>
  </p>

  <p>
    <%= f.label :book_count %><br/>
    <%= f.number_field :book_count %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/books/show.html.erb
<h1>Showing books details</h1>

<p><strong>Title: </strong><%= @book.title %></p>
<p><strong>Description: </strong><%= @book.description %></p>
<p><strong>Author: </strong><%= @book.author %></p>
<p><strong>Book_count: </strong><%= @book.book_count %></p>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to book", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">LIBRARY MANAGEMENT SYSTEM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  <p class ="notice"><%= notice %></p>
  <p class ="alert"><%= alert%></p>

    <%= yield %>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :book_count, style: "display: block" %>
    <%= form.number_field :book_count %>
  </div>

  <div>
    <%= form.label :mname, style: "display: block" %>
    <%= form.text_field :mname %>
  </div>

  <div>
    <%= form.label :titile, style: "display: block" %>
    <%= form.text_field :titile %>
  </div>

  <div>
    <%= form.label :issued_at, style: "display: block" %>
    <%= form.datetime_field :issued_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_library.html.erb
<div id="<%= dom_id library %>">
  <p>
    <strong>Role:</strong>
    <%= library.role %>
  </p>

  <p>
    <strong>Book count:</strong>
    <%= library.book_count %>
  </p>

  <p>
    <strong>Mname:</strong>
    <%= library.mname %>
  </p>

  <p>
    <strong>Titile:</strong>
    <%= library.titile %>
  </p>

  <p>
    <strong>Issued at:</strong>
    <%= library.issued_at %>
  </p>

</div>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libraries</h1>

<div id="libraries">
  <% @libraries.each do |library| %>
    <%= render library %>
    <p>
      <%= link_to "Show this library", library %>
    </p>
  <% end %>
</div>

<%= link_to "New library", new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @library %>

<div>
  <%= link_to "Edit this library", edit_library_path(@library) %> |
  <%= link_to "Back to libraries", libraries_path %>

  <%= button_to "Destroy this library", @library, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the Library Management system</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>